// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pokedex.Models;

#nullable disable

namespace Pokedex.Migrations
{
    [DbContext(typeof(PokedexContext))]
    [Migration("20220816205650_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Pokedex.Models.Pokemon", b =>
                {
                    b.Property<int>("PokemonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Details")
                        .HasColumnType("longtext");

                    b.Property<string>("EvolvesFrom")
                        .HasColumnType("longtext");

                    b.Property<string>("EvolvesTo")
                        .HasColumnType("longtext");

                    b.Property<int>("NationalPokedexNumber")
                        .HasColumnType("int");

                    b.Property<string>("PokemonName")
                        .HasColumnType("longtext");

                    b.Property<string>("PrimaryType")
                        .HasColumnType("longtext");

                    b.Property<string>("SecondaryType")
                        .HasColumnType("longtext");

                    b.HasKey("PokemonId");

                    b.ToTable("PokedexDatabase");

                    b.HasData(
                        new
                        {
                            PokemonId = 1,
                            Details = "It bears the seed of a plant on its back from birth. The seed slowly develops. Researchers are unsure whether to classify Bulbasaur as a plant or animal. Bulbasaur are extremely tough and very difficult to capture in the wild.",
                            EvolvesFrom = "n/a",
                            EvolvesTo = "Ivysaur",
                            NationalPokedexNumber = 1,
                            PokemonName = "Bulbasaur",
                            PrimaryType = "Grass",
                            SecondaryType = "Poison"
                        },
                        new
                        {
                            PokemonId = 2,
                            Details = "As Ivysaur takes in nutrients, a large flower blooms from the bulb on its back.",
                            EvolvesFrom = "Bulbasaur",
                            EvolvesTo = "Venusaur",
                            NationalPokedexNumber = 2,
                            PokemonName = "Ivysaur",
                            PrimaryType = "Grass",
                            SecondaryType = "Poison"
                        },
                        new
                        {
                            PokemonId = 3,
                            Details = "When Venusaur spreads out its large flower petals and absorbs the rays of the sun, it becomes energized.",
                            EvolvesFrom = "Ivysaur",
                            EvolvesTo = "n/a",
                            NationalPokedexNumber = 3,
                            PokemonName = "Venusaur",
                            PrimaryType = "Grass",
                            SecondaryType = "Poison"
                        },
                        new
                        {
                            PokemonId = 4,
                            Details = " A flame burns on the tip of its tail from birth. It is said that a Charmander dies if its flame never goes out.",
                            EvolvesFrom = "n/a",
                            EvolvesTo = "Charmeleon",
                            NationalPokedexNumber = 4,
                            PokemonName = "Charmander",
                            PrimaryType = "Fire",
                            SecondaryType = "n/a"
                        },
                        new
                        {
                            PokemonId = 5,
                            Details = "Charmeleon, the Flame Pokémon. It has razor-sharp claws and its tail is exceptionally strong.",
                            EvolvesFrom = "Charmander",
                            EvolvesTo = "Charizard",
                            NationalPokedexNumber = 5,
                            PokemonName = "Charmeleon",
                            PrimaryType = "Fire",
                            SecondaryType = "n/a"
                        },
                        new
                        {
                            PokemonId = 6,
                            Details = "Charizard, the Flame Pokémon. Charizard's powerful flame can melt absolutely anything.",
                            EvolvesFrom = "Charmeleon",
                            EvolvesTo = "n/a",
                            NationalPokedexNumber = 6,
                            PokemonName = "Charizard",
                            PrimaryType = "Fire",
                            SecondaryType = "Flying"
                        },
                        new
                        {
                            PokemonId = 7,
                            Details = "Squirtle. This Tiny Turtle Pokémon draws its long neck into its shell to launch incredible Water attacks with amazing range and accuracy. The blasts can be quite powerful.",
                            EvolvesFrom = "n/a",
                            EvolvesTo = "Wartortle",
                            NationalPokedexNumber = 7,
                            PokemonName = "Squirtle",
                            PrimaryType = "Water",
                            SecondaryType = "n/a"
                        },
                        new
                        {
                            PokemonId = 8,
                            Details = "Wartortle, the Turtle Pokémon. The evolved form of Squirtle. Its long furry tail is a symbol of its age and wisdom.",
                            EvolvesFrom = "Squirtle",
                            EvolvesTo = "Blastoise",
                            NationalPokedexNumber = 8,
                            PokemonName = "Wartortle",
                            PrimaryType = "Water",
                            SecondaryType = "n/a"
                        },
                        new
                        {
                            PokemonId = 9,
                            Details = "Blastoise, the Shellfish Pokémon. The evolved form of Wartortle. Blastoise's strength lies in its power, rather than its speed. Its shell is like armor and attacks from the hydro cannon on its back are virtually unstoppable.",
                            EvolvesFrom = "Wartortle",
                            EvolvesTo = "n/a",
                            NationalPokedexNumber = 9,
                            PokemonName = "Blastoise",
                            PrimaryType = "Water",
                            SecondaryType = "n/a"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
